---
name: eliud_pkg_text
description: Eliud package for rich text
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_text
version: 1.0.2+6
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  cloud_firestore: ^4.6.0
  collection: ^1.17.0
  datetime_picker_formfield: ^2.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_inappwebview: ^5.7.2+3
  flutter_widget_from_html: ^0.10.3
  flutter_widget_from_html_core: ^0.10.3
  html_editor_enhanced: ^2.5.1
  html: ^0.15.1
  http: ^0.13.5
  intl: ^0.18.1
  meta: ^1.8.0
  pointer_interceptor: ^0.9.3+3
  url_launcher: ^6.1.5
  eliud_core: ^1.0.7
  eliud_pkg_medium: ^1.0.1+6
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: 1.0.4+1
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
