name: eliud_pkg_text
description: Eliud package for rich text
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  html_editor_enhanced: 2.4.0+1
  flutter_widget_from_html: 0.8.3+1
# flutter_html: 2.1.5

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true
