---
name: eliud_pkg_text
description: "eliud_pkg_text is a package to provide text-functionality to eliud platform.\
  \ \"text\" is the broad name for html, markdown and the likes. More info at https://eliud.io"
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_text
version: 1.1.7
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core: ^1.1.6
  eliud_core_model: ^1.0.0
  eliud_core_main: ^1.0.2
  eliud_pkg_medium: ^1.1.6
  eliud_pkg_text_model: ^1.0.0
  eliud_core_helpers: ^1.0.0
  bloc: ^8.1.2
  html: ^0.15.4
  html_editor_enhanced: ^2.5.1
  flutter_bloc: ^8.1.3
  flutter_inappwebview: ^5.7.2+3
  flutter_widget_from_html: ^0.14.9
  flutter_widget_from_html_core: ^0.14.9
  pointer_interceptor: ^0.9.3+3
  universal_html: ^2.2.4
  url_launcher: ^6.2.2
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: ^1.1.7
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
