---
name: eliud_pkg_text
description: "eliud_pkg_text is a package to provide text-functionality to eliud platform.\
  \ \"text\" is the broad name for html, markdown and the likes. More info at https://eliud.io"
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_text
version: 1.1.5+6
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  html_editor_enhanced: ^2.5.1                                                                       # ANDROID IOS             WEB
  flutter_widget_from_html: ^0.14.9                                                                  # ANDROID IOS LINUX MACOS WEB WINDOWS
  flutter_widget_from_html_core: ^0.14.9                                                             # ANDROID IOS LINUX MACOS WEB WINDOWS
  url_launcher: ^6.2.2                                                                               # ANDROID IOS LINUX MACOS WEB WINDOWS
  eliud_core:                                                                                        # ANDROID IOS             WEB
    path: ../eliud_core
  eliud_core_model:                                                                                  # ANDROID IOS             WEB
    path: ../eliud_core_model
  eliud_core_main:                                                                                   # ANDROID IOS             WEB
    path: ../eliud_core_main
  eliud_pkg_medium:                                                                                  # ANDROID IOS             WEB
    path: ../eliud_pkg_medium
  eliud_pkg_text_model:                                                                              # ANDROID IOS             WEB
    path: ../eliud_pkg_text_model

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
