name: eliud_pkg_text
description: Eliud package for rich text
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  #flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  html_editor_enhanced:
    path: ../../html-editor-enhanced

  flutter_widget_from_html: 0.6.1
  flutter_html: 2.1.0

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true
