name: eliud_pkg_text
description: Eliud package for rich text
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  eliud_pkg_medium:
    path: ../eliud_pkg_medium

  html_editor_enhanced:
    path: ../../html-editor-enhanced

  flutter_widget_from_html: any
  flutter_widget_from_html_core: any
  pointer_interceptor: 0.9.3+3

  url_launcher: 6.1.5

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true
